name: Build Oneplus 8 Series (OxygenOS 13 A13) (XTD Kernel)

on:
  workflow_call:
  workflow_dispatch:

env:
  DEVICE_NAME : "oneplus_8_cn"
  DEVICE_CODENAME : "instantnoodle"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld"

  KERNEL_SOURCE : "https://github.com/nasbdh9/android_kernel_oneplus_sm8250.git"
  KERNEL_BRANCH : "lineage-20"

  CLANG_SOURCE : "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : "https://github.com/JackA1ltman/Google-GCC-Android-4.9.git"
  GCC_64_BRANCH : "aarch64"
  GCC_32_SOURCE : "https://github.com/JackA1ltman/Google-GCC-Android-4.9.git"
  GCC_32_BRANCH : "arm32"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "kona-perf_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "false"
  KERNELSU_AUTO_FORK : "rsuntk"

  SUSFS_ENABLE : false
  SUSFS_FIXED : false
  SUSFS_UPDATE : false

  AK3_SOURCE : "https://github.com/JackA1ltman/OP8_AnyKernel3.git"
  AK3_BRANCH : "main"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "lineage20_a13"

  PYTHON_VERSION: "3"

  PACK_METHOD: "Anykernel3"

  KERNELSU_METHOD: "shell"

  PATCHES_SOURCE: ""
  PATCHES_BRANCH: ""

  SUSFS_FOLDER_FIXED: ""
  SUSFS_155_FIXED: ""
  SUSFS_LATEST_FIXED: ""

  REKERNEL_ENABLE: "false"

  HOOK_METHOD: "syscall"
  HOOK_OLDER: "false"

  KPM_ENABLE: "false"
  KPM_PATCH_SOURCE: ""

  BASEBAND_GUARD_ENABLE: "false"
  BASEBAND_GUARD_BOOT: "false"

  HIDE_STUFF: "false"

  GENERATE_DTB: "false"
  GENERATE_CHIP: "qcom"

  BUILD_DEBUGGER: "true"
  SKIP_PATCH: "true"

  BUILD_OTHER_CONFIG: "false"
  MERGE_CONFIG_FILES: ""

  FREE_MORE_SPACE: "false"

jobs:
  build-kernel:
    name: Oneplus 8 Series (OxygenOS 13 A13) (XTD Kernel)
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          echo "CONFIG_CPU_BIG_ENDIAN=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_COMPAT_VDSO=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_LTO_NONE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_INIT_STACK_NONE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🔧 Patch Hide Stuff
        uses: ./.github/workflows/patch-hide-stuff

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files